### ISSUE TITLE
Enable https not working

### ISSUE THREAD

**Issue by c0mputerking** [digitalfondue/lavagna#97]
Running lavagna-1.1-M7 on Debian 9

I tried checking Enable http strict transport security header in the admin panel, to hopefully enable https and now i can no longer connect to Lavanga even after restarting the application as suggested in the log.

If i try with https i get this error in my browser 

> Secure Connection Failed
> 
> An error occurred during a connection to list-3.solar.computerking.ca:8080. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG
> 
>     The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
>     Please contact the website owners to inform them of this problem.

If i try with http it lets me login but i then i get this error in my browser

> HTTP ERROR 403
> 
> Problem accessing /login/password/. Reason:
> 
>     token is not equal to expected
> 
> Powered by Jetty://

This is what is printed on the console
 
`22:59:17.830 [qtp1642534850-17] WARN  io.lavagna.web.security.HSTSFilter - The base application url http://list-3.solar.somedomain.com:8080/ does not begin with https:// . It's a mandatory requirement if you want to enable full https mode.`

**Comment by syjer** [comment]
hi @c0mputerking , the addition by the application of the hsts header is a feature that we want to remove, as you have noticed is quite hard to configure. It's something that should be done at the proxy level.

I would advise you to go in the database and remove the configuration key.

```sql
delete from LA_CONF  where CONF_KEY = 'USE_HTTPS'
```

**Comment by c0mputerking** [comment]
I just restored from a backup, but thank you for the hint about the database entry ... I still need to get https going, however i did not find any howto or info in the docs about setting up a proxy, is this documented somewhere? or is this just something people with more java experience know how to do :)

**Comment by syjer** [comment]
@c0mputerking , normally you would setup a reverse proxy (like nginx or haproxy) that handle the https termination.

So you would have something like that: 

```
[internet] <- https -> [reverse proxy] <- http -> [lavagna]
```

**Comment by c0mputerking** [comment]
Ok thank you i will give it a go

**Comment by SitoCH** [comment]
The best way to setup a reverse proxy with SSL is to use Docker, if you know it you should try that way.
This is a sample docker-compse (it uses Let's Encrypt to generate automatically the certificates so it's all free):

```
nginx-proxy:
    privileged: true
    restart: always
    net: host
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/pki/tls/private:/etc/nginx/certs

letsencrypt-nginx-proxy:
    privileged: true
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy
    volumes_from: [nginx-proxy]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - /etc/pki/tls/private:/etc/nginx/certs:rw 

lavagna:
    privileged: true
    restart: always
    container_name: "lavagna"
    image: digitalfondue/lavagna
    links:
        - "mysql:mysql"
    environment:
        - "VIRTUAL_HOST=[server url]"  
        - "VIRTUAL_PORT=8080" 
        - "LETSENCRYPT_HOST=[server url]"
        - "LETSENCRYPT_EMAIL=[your e-mail]"
        - "DB_DIALECT=MYSQL"
        - "DB_URL=[jdbc connection string]"
        - "DB_USER=[user]"
        - "DB_PASS=[password]"
        - "SPRING_PROFILE=prod"
    mem_limit: 260m
```
